aero:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Drive Controller
  drive_controller:
    type: robot_drive_controllers/Skid4WheelDriveController
    left_joint_name: left_wheels_motor
    right_joint_name: right_wheels_motor
