aero:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Drive Controller
  drive_controller:
    type: robot_drive_controllers/Skid4WheelDriveController
    front_left_joint_name: joint_front_left_wheel
    back_left_joint_name: joint_back_left_wheel
    front_right_joint_name: joint_front_right_wheel
    back_right_joint_name: joint_back_right_wheel
