aero:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Drive Controller
  drive_controller:
    type: robot_drive_controllers/Skid4WheelDriveController
    left_joint_name: joint_front_left_wheel
    right_joint_name: joint_front_right_wheel
    rotations_per_meter: 1.0
    base_width: 0.554
    base_length: 0.52