scan_filter_chain:
- name: laser_cutoff
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.61
    upper_angle: 1.61
- name: laser_shutter
  type: aero_control/LaserShutterFilter
#- name: small_object_filter
#  type: aero_control/LaserSmallObjectFilter
#  params:
#    max_object_size: 5
#    min_surrounding: 5
#    max_depth_variance: 0.1
