pub_rate: 1.0
base_path: ''
analyzers:
  Compuer:
    type: AnalyzerGroup
    path: Computer
    analyzers:
      CPU0:
        type: GenericAnalyzer
        path: CPU 0
        startswith: 'computer_sensors_monitor: coretemp-isa-0000/'
        remove_prefix: 'computer_sensors_monitor: coretemp-isa-0000 '
      CPU1:
        type: GenericAnalyzer
        path: CPU 1
        startswith: 'computer_sensors_monitor: coretemp-isa-0001/'
        remove_prefix: 'computer_sensors_monitor: coretemp-isa-0001 '
      Other:
        type: DiscardAnalyzer
        path: Other
        startswith: 'computer_sensors_monitor: nct6776'
  Vision:
    type: AnalyzerGroup
    path: Vision
    analyzers:
      UpperStereo:
        type: AnalyzerGroup
        path: Upper Stereo
        analyzers:
          LeftCamera:
            type: GenericAnalyzer
            path: Left Camera
            startswith: 'aero/upper_stereo/left_camera: '
            remove_prefix: 'aero upper_stereo left_camera: '
          RightCamera:
            type: GenericAnalyzer
            path: Right Camera
            startswith: 'aero/upper_stereo/right_camera: '
            remove_prefix: 'aero upper_stereo right_camera: '
          Sync:
            type: GenericAnalyzer
            path: Camera Sync
            startswith: 'aero/upper_stereo/camera_sync: '
            remove_prefix: 'aero upper_stereo camera_sync: '
  Battery:
    type: GenericAnalyzer
    path: Battery
    startswith: 'Battery Pack'
