pub_rate: 1.0
base_path: ''
analyzers:
  Compuer:
    type: GenericAnalyzer
    path: Computer
    find_and_remove_prefix: 'computer_sensors_monitor: '
  Vision:
    type: AnalyzerGroup
    path: Vision
    analyzers:
      UpperStereo:
        type: AnalyzerGroup
        path: Upper Stereo
        analyzers:
          LeftCamera:
            type: GenericAnalyzer
            path: Left Camera
            startswith: 'aero/upper_stereo/left_camera: '
            remove_prefix: 'aero upper_stereo left_camera: '
          RightCamera:
            type: GenericAnalyzer
            path: Right Camera
            startswith: 'aero/upper_stereo/right_camera: '
            remove_prefix: 'aero upper_stereo right_camera: '
          Sync:
            type: GenericAnalyzer
            path: Camera Sync
            startswith: 'aero/upper_stereo/camera_sync: '
            remove_prefix: 'aero upper_stereo camera_sync: '
#  Battery:
#    type: GenericAnalyzer
#    path: Battery
#    find_and_remove_prefix: 'mk3_battery_monitor: '
