#sensors:
#  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    point_cloud_topic: /aero/lower_stereo/points2
#    max_range: 10.0
#    point_subsample: 1
#    padding_offset: 0.1
#    padding_scale: 1.0
#    filtered_cloud_topic: filtered_cloud