<?xml version="1.0"?>

<root xmlns:xacro="http://ros.org/wiki/xacro">
       
  <!-- Colors -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="Green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>

  <material name="Gray">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <material name="DarkGray">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  
  <material name="Yellow">
    <color rgba="0.8 0.8 0.0 1.0"/>
  </material>

  <property name="M_PI" value="3.1415926535897931" />

  <property name="base_length" value="0.806" />
  <property name="base_width" value="0.419" />
  <property name="base_height" value="0.228" />

  <property name="wheel_diameter" value="0.32" />
  <property name="wheel_width" value="0.11" />
  <property name="wheel_base_width" value="0.546" />
  <property name="wheel_base_length" value="0.558" />
  <property name="wheel_base_link_height" value="0.0381" />

  <property name="top_plate_length" value="0.549" />


  <xacro:macro name="husky_wheel" params="fb lr parent translateX translateY flipY"> <!--fb : front, back ; lr: left, right -->
    <link name="${fb}_${lr}_wheel">
      <collision>
	<origin xyz="0 0 0" rpy="${flipY*M_PI + M_PI/2} 0 0" /> 
	<geometry>
	  <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
	</geometry>
      </collision>
      <visual>
	<origin xyz="0 0 0" rpy="${flipY*M_PI + M_PI/2} 0 0" /> 
	<geometry>
	  <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
	</geometry>
	<material name="DarkGray" />
      </visual>
      <inertial>
	<origin xyz="0 0 0" rpy="0 0 0"/>
	<mass value="5"/>
	<inertia
	    ixx="1.0" ixy="0.0" ixz="0.0"
	    iyy="0.0" iyz="0.0"
	    izz="0.0"/>
      </inertial>
    </link>

    <joint name="joint_${fb}_${lr}_wheel" type="continuous">
      <parent link="${parent}"/>
      <child link="${fb}_${lr}_wheel"/>
      <origin xyz="${translateX * wheel_base_length/2} ${translateY * wheel_base_width/2} ${wheel_base_link_height}" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>


    <transmission name="${fb}_${lr}_wheel_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint_${fb}_${lr}_wheel"/>
      <actuator name="${lr}_wheel_motor">
	<hardwareInterface>EffortJointInterface</hardwareInterface>
	<mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>



  <xacro:macro name="husky">
    <link name="base_footprint">
      <collision>
	<origin xyz="0 0 0" rpy="0 0 0" />
	<geometry>
	  <box size="0.001 0.001 0.001" />
	</geometry>
      </collision>
      <visual>
	<origin xyz="0 0 0" rpy="0 0 0" />
	<geometry>
	  <box size="0.001 0.001 0.001" />
	</geometry>
	<material name="Blue" />
      </visual>
      <inertial>
	<origin xyz="0 0 0" rpy="0 0 0"/>
	<mass value="1"/>
	<inertia
	    ixx="1.0" ixy="0.0" ixz="0.0"
	    iyy="1.0" iyz="0.0"
	    izz="1.0"/>
      </inertial>
    </link>

    <xacro:static_transform parent="base_footprint" name="base_link" xyz="0 0 ${wheel_diameter/2-wheel_base_link_height}" rpy="0 0 0">
      <collision>
	<origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
	<geometry>
	  <box size="${base_length} ${base_width} ${base_height}" />
	</geometry>
      </collision>
      <visual>
	<origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
	<geometry>
	  <box size="${base_length} ${base_width} ${base_height}" />
	</geometry>
	<material name="Yellow" />
      </visual>
      <inertial>
	<origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
	<mass value="1"/>
	<inertia
	    ixx="1.0" ixy="0.0" ixz="0.0"
	    iyy="1.0" iyz="0.0"
	    izz="1.0"/>
      </inertial>
    </xacro:static_transform>

    <xacro:static_transform parent="base_link" name="top_plate" xyz="0 0 ${base_height}" rpy="0 0 0">
      <collision>
	<origin xyz="0 0 0" rpy="0 0 0" />
	<geometry>
	  <box size="${top_plate_length} ${base_width} 0.02" />
	</geometry>
      </collision>
      <visual>
	<origin xyz="0 0 0" rpy="0 0 0" />
	<geometry>
	  <box size="${top_plate_length} ${base_width} 0.02" />
	</geometry>
	<material name="DarkGray" />
      </visual>
      <inertial>
	<origin xyz="0 0 0" rpy="0 0 0"/>
	<mass value="1"/>
	<inertia
	    ixx="1.0" ixy="0.0" ixz="0.0"
	    iyy="1.0" iyz="0.0"
	    izz="1.0"/>
      </inertial>
    </xacro:static_transform>


    <!-- WHEEL macros -->
    <husky_wheel fb="back" lr="left" parent="base_link" translateX="-1" translateY="1" flipY="-1"/>
    <husky_wheel fb="back" lr="right" parent="base_link" translateX="-1" translateY="-1" flipY="-1"/>
    <husky_wheel fb="front" lr="left" parent="base_link" translateX="1" translateY="1" flipY="-1"/>
    <husky_wheel fb="front" lr="right" parent="base_link" translateX="1" translateY="-1" flipY="-1"/>

  </xacro:macro>


</root>
