<?xml version="1.0" encoding="utf-8"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
      xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
      xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
      xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find aero_description)/urdf/simple_transform.urdf.xacro" />
  <xacro:include filename="$(find aero_description)/urdf/manta_camera.urdf.xacro" />

  <property name="camera_rail_length" value="0.0508" /><!--front to back -->
  <property name="camera_rail_height" value="0.0254" />


  <xacro:macro name="stereo_camera_pair" params="prefix parent xyz rpy camera_base_length camera_tilt">
    <xacro:static_transform parent="${parent}" name="${prefix}/camera_rail" xyz="${xyz}" rpy="${rpy}">
    <visual>
      <origin xyz="0 0 ${camera_rail_height/2}" rpy="0 0 0" />
      <geometry>
	<box size="${camera_rail_length} ${camera_base_length-manta_camera_width} ${camera_rail_height}" />
      </geometry>
      <material name="Blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${camera_rail_height/2}" rpy="0 0 0" />
      <geometry>
	<box size="${camera_rail_length} ${camera_base_length-manta_camera_width} ${camera_rail_height}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </xacro:static_transform>
  <xacro:static_transform parent="${prefix}/camera_rail" name="${prefix}/camera_rail_tilt" xyz="0 0 ${camera_rail_height/2}" rpy="0 ${camera_tilt} 0">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="0 0 0" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="0 0 0" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </xacro:static_transform>

<!--    <xacro:manta_cam_v0 frame_name="${prefix}/left_camera" parent="${prefix}/camera_rail_tilt" camera_name="${prefix}/left">
      <origin xyz="0.03 ${camera_base_length/2} ${manta_camera_height/2+camera_rail_height/2}" rpy="0 0 0" />
    </xacro:manta_cam_v0> 
    
    <xacro:manta_cam_v0 frame_name="${prefix}/right_camera" parent="${prefix}/camera_rail_tilt" camera_name="${prefix}/right">
      <origin xyz="0.03 ${-camera_base_length/2} ${manta_camera_height/2+camera_rail_height/2}" rpy="0 0 0" />
    </xacro:manta_cam_v0> -->

    <xacro:static_transform parent="${prefix}/camera_rail_tilt" name="${prefix}/optical_frame" xyz="0.03 0 ${manta_camera_height/2+camera_rail_height/2}" rpy="${-M_PI/2} 0 ${-M_PI/2}">
      <visual>
	<geometry>
	  <box size="0 0 0" />
	</geometry>
	<material name="Clear">
	  <color rgba="0 0 0 0"/>
	</material>
      </visual>
      <collision>
	<geometry>
	  <box size="0 0 0" />
	</geometry>
      </collision>
      <inertial>
	<origin xyz="0 0 0" rpy="0 0 0"/>
	<mass value="1"/>
	<inertia
	    ixx="1.0" ixy="0.0" ixz="0.0"
	    iyy="1.0" iyz="0.0"
	    izz="1.0"/>
      </inertial>
    </xacro:static_transform>


    <gazebo reference="${prefix}/camera_rail_tilt">
      <sensor type="multicamera" name="${prefix}/camera">
	<update_rate>30.0</update_rate>
	<camera name="left">
	  <pose>0.06 ${camera_base_length/2} ${manta_camera_height/2+camera_rail_height/2} 0 0 0</pose>
	  <horizontal_fov>1.3962634</horizontal_fov>
	  <image>
	    <width>800</width>
	    <height>800</height>
	    <format>R8G8B8</format>
	  </image>
	  <clip>
	    <near>0.02</near>
	    <far>300</far>
	  </clip>
	  <noise>
	    <type>gaussian</type>
	    <mean>0.0</mean>
	    <stddev>0.007</stddev>
	  </noise>
	</camera>
	<camera name="right">
	  <pose>0.06 ${-camera_base_length/2} ${manta_camera_height/2+camera_rail_height/2} 0 0 0</pose>
	  <horizontal_fov>1.3962634</horizontal_fov>
	  <image>
	    <width>800</width>
	    <height>800</height>
	    <format>R8G8B8</format>
	  </image>
	  <clip>
	    <near>0.02</near>
	    <far>300</far>
	  </clip>
	  <noise>
	    <type>gaussian</type>
	    <mean>0.0</mean>
	    <stddev>0.007</stddev>
	  </noise>
	</camera>
	<plugin name="${prefix}/camera_controller" filename="libgazebo_ros_multicamera.so">
	  <alwaysOn>true</alwaysOn>
	  <updateRate>0.0</updateRate>
	  <cameraName>${prefix}/camera</cameraName>
	  <imageTopicName>image_raw</imageTopicName>
	  <cameraInfoTopicName>camera_info</cameraInfoTopicName>
	  <frameName>${prefix}/optical_frame</frameName>
	  <hackBaseline>0.07</hackBaseline>
	  <distortionK1>0.0</distortionK1>
	  <distortionK2>0.0</distortionK2>
	  <distortionK3>0.0</distortionK3>
	  <distortionT1>0.0</distortionT1>
	  <distortionT2>0.0</distortionT2>
	</plugin>
      </sensor>
    </gazebo>

  </xacro:macro>
  
</root>
